name: Elise Aguilar Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87102
title: FIRED UP BY THE THINGS THAT MATTER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33342e'
    - '#d4ddcc'
    - '#575f50'
    - '#bd8a51'
    - '#966a3d'
  brandStrength: 0.7271067856345326
  lightness: 0.4878942552022636
  saturation: 0.31659291917458177
  rhythmicContrast: 0.1733323319349438
purpose: []
